### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by garyernestdavis** [openjournals/brief-ideas#103]
My article "Those who walk among us" http://beta.briefideas.org/ideas/013f3addfa3f5a7db2871a922349b3dd, DOI 10.5281/zenodo.15452 does not seem to be listed on the Journal of Brief Ideas. I have two other articles there, but this one seems to be absent.

For that reason I tried submitting it slightly differently & under a different title -  'Is there a "Homo systemicus" species walking benignly among us?' -  but this submission was not accepted into the Journal of Brief Ideas (presumably because it's too similar to DOI 10.5281/zenodo.15452)

Can someone please explain why "Those who walk among us" http://beta.briefideas.org/ideas/013f3addfa3f5a7db2871a922349b3dd, DOI 10.5281/zenodo.15452 is not showing on the Journal?

Many thanks.

Gary Davis

**Comment by physicsdavid** [comment]
Your article does appear to be showing up. If you search for it by title or
relevant search terms, it appears in the results list. It also shows up by
going to the direct link you mentioned.

Best wishes,
David

**Comment by garyernestdavis** [comment]
David,

thanks, I see that. However, search as I might I cannot find it on the list of All Ideas. In other words, if one knew to look for it, one would find it by a search, but it does not appear, so far as I can tell, on the list of accepted ides, whereas my other two do so appear (they even have votes).

Gary Davis

**Comment by physicsdavid** [comment]
Gary,
I see now what has happened. The editorial team felt the idea was not really contributing to the development of research in the field but was submitted before we were moderating contributions. Hence the idea remains in the journal but isn't shown in the main list of ideas.
David

**Comment by garyernestdavis** [comment]
OK, thanks David. I'm glad that you are now moderating ideas. 

Best wishes for the Journal.

Gary
