### ISSUE TITLE
Twitter?

### ISSUE THREAD

**Issue by spencertweedy** [openjournals/brief-ideas#110]
Hi there. I was just thinking it might be nice to have a Twitter-a-la-RSS feed. Carry on...

**Comment by physicsdavid** [comment]
There is a Twitter account that includes many of the new ideas. It is called @BriefJournal. You can also subscribe to an RSS feed of the ideas here: http://beta.briefideas.org/ideas.atom

**Comment by spencertweedy** [comment]
Awesome. Thank you.
