### ISSUE TITLE
HTML tags in title are displayed correctly in preview but not in final Brief Idea.

### ISSUE THREAD

**Issue by grputland** [openjournals/brief-ideas#114]
This applies to the Brief Idea as displayed at e.g. http://beta.briefideas.org/ideas/db017aafc9ef680d0549e46e25aa8964 and http://dx.doi.org/10.5281/zenodo.16280 .

**Comment by arfon** [comment]
Yeah, I noticed that. HTML tags shouldn't really be used in the title sorry.

**Comment by grputland** [comment]
Well, if HTML tags - especially such innocuous ones as single quotes - should not be used, may I respectfully suggest that they should not be displayed correctly in the preview so as to give the misleading impression that they can be used? And if that suggestion is rejected, may I respectfully ask what previews are for?

**Comment by arfon** [comment]
>  may I respectfully suggest that they should not be displayed correctly in the preview so as to give the misleading impression that they can be used?

Yep, that's a totally fair point. Sorry for being a little over-zealous closing this. To be honest I hadn't expected HTML to be used here (normal ASCII quotes would have worked fine here instead of HTML ones). I'll work on a fix for this for the preview.

**Comment by arfon** [comment]
@grputland - this should be fixed now.

**Comment by grputland** [comment]
Many thanks.
