### ISSUE TITLE
On the encouraged use of Brief Ideas

### ISSUE THREAD

**Issue by samuell** [openjournals/brief-ideas#124]
I have seen the service being called "patent trolling, but for scientific purposes". I think there is a possible risk that the site could be used that way. On the other hand, I also see that it could be a perfect medium for "brainstorming" around great ideas.

Thus, are you planning on some way to actively encourage "brainstorming like" usage pattern, as opposed to something like a "patent trolling" one?

**Comment by physicsdavid** [comment]
I hadn't actually seen the "patent trolling" comment but I see the point. Fortunately, there is no real way to monetize the publishing of an idea in the same way as patent trolling so it doesn't quite follow perfectly. (Yes, I see the ways in which it does, however.)

We are definitely encouraging brainstorming, such as through our project with the Perimeter Institute "Convergence" conference ( http://briefideas.org/convergence ) which is all about brainstorming. But if you have specific suggestions about better ways to encourage this, please so let us know!
