### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by fjrrest** [openjournals/brief-ideas#130]
I just submitted the article "The share of Open Access Journals (OAJ) and Open Access Articles (OAA) charging Article Processing Charges (APC). Data from the Austrian Science Fund (FWF) 2013 to 2015" 
I actually also wanted to attach the underlying data (excel format)  but I go an error message. Could you do it for me? If so I would send you the file.
Many thanks,
Best, Falk Reckling

**Comment by arfon** [comment]
Hi @fjrrest - you should be able to attach this as a zipped file. Would you mind try to resubmit again with the data zipped up?

**Comment by fjrrest** [comment]
ok, thanks, but then I have to sumbit again because I cannot find the
submitted version im my account ... best, falk

2015-09-03 10:24 GMT+02:00 Arfon Smith <notifications@github.com>:

**Comment by fjrrest** [comment]
I have the article submitted again, it works ! Please delete the first
version.
Many thanks,
Falk

2015-09-03 10:53 GMT+02:00 fjrrest <fjrrest@gmail.com>:

**Comment by arfon** [comment]
Great. Thanks for re-submitting.
