### ISSUE TITLE
Hello one more authers?

### ISSUE THREAD

**Issue by harrisonhanfei** [openjournals/brief-ideas#131]
Hello, I found now the paper can be published by two authors (http://beta.briefideas.org/ideas/5387495e30493fec826d81f58a973d8f). But I fail to find how to do that. Could you kindly tell me how to submit an idea with two authors?

**Comment by arfon** [comment]
Hi @harrisonhanfei - after creating the idea (on the initial form) there's a second screen that allows you to add more authors.

Sorry it took me so long to get to this question!
