### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by mickofemsworth** [openjournals/brief-ideas#133]
I've just submitted an idea to brief-ideas. What happens next? There's no acknowledgment or paper in my collection?

Thanks for your help
Michael Wood
mickofemsworth@gmail.com

**Comment by danielskatz** [comment]
this should be linked to https://github.com/openjournals/brief-ideas/issues/143 and https://github.com/openjournals/brief-ideas/issues/144

**Comment by arfon** [comment]
Fixed in #143
