### ISSUE TITLE
The absolute Coordinate system and the absolute Time of the Universe

### ISSUE THREAD

**Issue by guettinger** [openjournals/brief-ideas#134]
Urheber nach UrhG und © Hanspeter Güttinger, 16. November 2015, all rights reserved

Is it possible to change the Theory of relativity?

Albert Einstein formulated:

1st Postulate - Principle of relativity:
All inertial systems are equal for the description of natural processes.
The laws of nature have the same form in any inertial systems.

2nd Postulate - Constancy of the speed of light:
In all inertial systems light spreads in vacuum isotropic and regardless of the current movement of the light source with the speed of c = 299 792 458 m/s.

The two principles do not necessarily follow from the observations. "There is no logical way, which leads to the elementary laws", says EINSTEIN, "but only intuition, resting on sympathetic
understanding of experience, this can reach them."
It is not possible to prove the two principles as the only possible and correct.
To confirm a theory a deductive approach is necessary to draw conclusions from the theories principles that can be verified experimentally.
So far, all predictions have been confirmed by the experiment.

Quoted from: Metzler Physik SII - 4. Auflage 2007 Schroedel Verlag, Germany
_______________________________________________________________________________

100 years later we know the origin and structure of the universe with very high probability.
The outstanding event is the Big Bang, plus the accelerated expansion of space.
The value of the Hubble constant that is changing over time is known.

The big bang point, taking into account the Planck units (from the Planck time), would lead to an absolute space coordinate system I think.
Preferably a spherical coordinate system, assuming the universe as spherical.

The physics and physicists determine the consequences.
The first consequence:
There is an absolute space coordinate system with the formulated assumptions.
Second consequence:
There is an absolute time of the universe.

Hanspeter Guettinger formulates:

1st Postulate – The absolute Coordinate system of the Universe:
The coordinate system uses the big bang point, taking into account the Planck units (from the Planck time). Preferably a spherical coordinate system, assuming the universe as spherical.

2nd Postulate – The absolute time of the Universe:
This time is known and can be calculated continuously further.

Translation to English, by Hanspeter Guettinger.

[The absolute coordinate system of the universe.pdf](https://github.com/openjournals/brief-ideas/files/76183/The.absolute.coordinate.system.of.the.universe.pdf)

**Comment by arfon** [comment]
Closing as this should be submitted to the journal website: http://beta.briefideas.org/
