### ISSUE TITLE
Tags are not case sensitive while tag search is

### ISSUE THREAD

**Issue by vlimant** [openjournals/brief-ideas#135]
Dear developer, many thanks for the great product !

I have noticed that one cannot enter a tag with capitals (it gets transformed to lower case automatically) and the search by tag is itself case sensitive 
http://beta.briefideas.org/search?tags=LHC
is not the same as 
http://beta.briefideas.org/search?tags=lhc
and de-facto, the first search could never give any answer ; i.e. the capitalized LHC tag can never be made.
I would make search non-case sensitive and have both search return the same result.

 Regards,
Jean-Roch

**Comment by arfon** [comment]
Fixed in https://github.com/openjournals/brief-ideas/pull/137
