### ISSUE TITLE
inconsistent case sensitivity in tags

### ISSUE THREAD

**Issue by cranmer** [openjournals/brief-ideas#136]
It seems that while tags cannot be made case sensitive (it's automatically set to lower case by the service), the search itself IS case sensitive

http://beta.briefideas.org/search?tags=dslhc

is different than

http://beta.briefideas.org/search?tags=DSLHC

**Comment by arfon** [comment]
Huh, good spot. I can fix that.

**Comment by cranmer** [comment]
Thanks!
