### ISSUE TITLE
Multiple authors?

### ISSUE THREAD

**Issue by puh32** [openjournals/brief-ideas#140]
Hi, 

I have a 200-word idea which I've developed together with three colleagues. It's ready to go.

However, I could not find a way to indicate that we are four co-authors behind the idea.

There must be a way for this, since I've seen some ideas with more than 1 authors (e.g., http://beta.briefideas.org/ideas/42d8749002898fcf9e86b010fe397c88).

How is it done?

Yours sincerely,

Henrik Nilsson
University of Gothenburg

**Comment by arfon** [comment]
Hi @puh32 - this is possible - you can invite authors after you click 'save idea'.

I should update the docs to reflect this.

**Comment by puh32** [comment]
Thanks for your reply.

I have now invited the others, and they accepted. However, the author order came out the wrong way and now reflects the time when the co-authors accepted to join the idea (last in -> first co-author). Is it possible to change this? (It is not a big deal though.)

**Comment by arfon** [comment]
> I have now invited the others, and they accepted. However, the author order came out the wrong way and now reflects the time when the co-authors accepted to join the idea (last in -> first co-author). Is it possible to change this? (It is not a big deal though.)

Oh good point. I should fix that. I've opened an issue in #141
