### ISSUE TITLE
Long comments won't submit, no error

### ISSUE THREAD

**Issue by cranmer** [openjournals/brief-ideas#142]
It seems that you can't add comments beyond some character or word count. That's fine if it's done on purpose, but there is no error given or word countdown.

I was able to submit the comment if I split the text into two parts:
http://beta.briefideas.org/ideas/ff0489d51bdb17359cef823c1d6b7029

**Comment by arfon** [comment]
Huh, weird. It should report an error: https://github.com/openjournals/brief-ideas/blob/master/app/models/comment.rb#L10-L13

Lemme dig into it and see what I can do.
