### ISSUE TITLE
Status of JoBI submission requested

### ISSUE THREAD

**Issue by RJNemiroff** [openjournals/brief-ideas#143]
Yesterday, I submitted a brief idea to the Journal of Brief Ideas. I screen told me this idea would be placed under review, which is fine. Today, though, I can find no sign of my submission. It is not even in "Your Ideas". Also, I did not get an email verification of my submission. So my question is -- has this idea been lost or is it really under review? I am sorry to bother you but I wanted to clarify what is going on. Thank you for any additional information you can provide. - Robert Nemiroff

**Comment by danielskatz** [comment]
this is almost the same as an issue I just created - https://github.com/openjournals/brief-ideas/issues/144

**Comment by arfon** [comment]
Thanks for the feedback @RJNemiroff - this was fixed in #146

**Comment by dunldj** [comment]
Hi @arfon. I submitted something last week and didn't get receive email notification. Or any trace of it  under the "your ideas" tab; much like the original post in #143. Any idea of it went through or if I'll need to resubmit?

**Comment by QCAInteractiveMedia** [comment]
I can't see any sign of it in the submissions list but perhaps @arfon might have an extra way to check the back end.

**Comment by physicsdavid** [comment]
I can't see any sign of it in the submissions list but perhaps @arfon can find something else in the back end.

**Comment by arfon** [comment]
I don't see anything. Could you try submitting again?

**Comment by dunldj** [comment]
@physicsdavid and @arfon Thanks for checking, sorry for the trouble. Will do!
