### ISSUE TITLE
request to fix two typos in a brief idea

### ISSUE THREAD

**Issue by danielskatz** [openjournals/brief-ideas#145]
In http://beta.briefideas.org/ideas/2ddde9c0ef80c211115d18420f4a06f3, I wrote "but It also would be interested" which should have been "but it also would be interesting".  Can this be fixed?

**Comment by danielskatz** [comment]
I note https://github.com/openjournals/brief-ideas/issues/84 is similar to this

**Comment by arfon** [comment]
@danielskatz - I think we're still waiting on Zenodo for versioned DOI support: https://github.com/openjournals/brief-ideas/issues/84#issuecomment-109111064

I've made the update to the text on the site though.
