### ISSUE TITLE
Need to un-submit a version of idea

### ISSUE THREAD

**Issue by balicea** [openjournals/brief-ideas#153]
Recently, I (Bradly Alicea) submitted an idea called "Playing Games with Ideas: when Epistomological beliefs pay off". This version has a series of spelling errors, which I did not catch in time. I then submitted a replacement idea "Playing Games with Ideas: when epistemology pays off", which corrected the previous errors. If you could unsubmit or not accept the first submission, it would be appreciated. Thanks.

**Comment by physicsdavid** [comment]
Hi Bradly - We'll just allow the second version through the process...

Thanks,
David
