### ISSUE TITLE
Regarding publishing in Journal of Brief Ideas

### ISSUE THREAD

**Issue by sattaravy** [openjournals/brief-ideas#155]
Dear Journal of Brief Ideas,

I am a senior researcher in the field of proteomics (mass spectrometry). I have a number of innovative research ideas on improving the current proteomics research methods. As I am already retired, I no longer have access to research funding (nor am I interested in applying for further funding) to materialise these ideas.

I came across your journal by chance, and I am very intrigued by your publication model. I’d really appreciate if you can kindly provide answers to my following enquiries:

1. I’d be very interested in publishing my research ideas so that other scientists in the proteomics research field can use these ideas and improve their research. This would also allow me to receive credit for coming up with these ideas. I do not have much research data to support my ideas, and I’m wondering if Journal of Brief Ideas would publish a paper based predominately on innovative ideas only?

2. Does Journal of Brief Ideas have a current impact factor?

3. Is Journal of Brief Ideas a peer-reviewed journal? If so, what is the peer-review process?

4. Is there a publication cost?

I’d be grateful if you can kindly response to my enquiries. Looking forward to hearing from you.

Yours Sincerely,

Professor James Su

**Comment by arfon** [comment]
/ cc @physicsdavid

**Comment by physicsdavid** [comment]
Dear Prof. Su,

I'll answer your questions in turn.

1. Yes, the Journal of Brief Ideas would publish a paper based on an innovative idea, even if there isn't yet experimentation to back it up. One of the missions of the journal is to help spread those ideas that individuals can't pursue themselves for whatever reason, but might still contribute to the progress of science.

You would receive credit for your ideas in the sense that each submission has a time-stamped DOI with author credit and is permanently archived for reference through Zenodo.

2. The Journal does not currently have an impact factor as registering for that costs real money and we run the Journal on a shoestring as a service to the community.

3. The Journal is not peer-reviewed as such, as one of the aims of the journal is to get ideas into circulation quickly. However all submissions are checked for general legitimacy before acceptance. That means we have about a 50% acceptance rate for ideas. After submission, there is a kind of post-publication review in the sense that readers can rate a submission by "liking" the submission, or can leave a comment on the submission.

4. There is no publication cost. All costs of running the journal are absorbed personally by the founders. 

Regards,
David Harris

**Comment by sattaravy** [comment]
Dear David,


Thank you and appreciate your response. I will consider submitting an article if I believe the contents are appropriate.


Best Regards,

James Su

________________________________



Dear Prof. Su,

I'll answer your questions in turn.

  1.  Yes, the Journal of Brief Ideas would publish a paper based on an innovative idea, even if there isn't yet experimentation to back it up. One of the missions of the journal is to help spread those ideas that individuals can't pursue themselves for whatever reason, but might still contribute to the progress of science.

You would receive credit for your ideas in the sense that each submission has a time-stamped DOI with author credit and is permanently archived for reference through Zenodo.

  1.  The Journal does not currently have an impact factor as registering for that costs real money and we run the Journal on a shoestring as a service to the community.

  2.  The Journal is not peer-reviewed as such, as one of the aims of the journal is to get ideas into circulation quickly. However all submissions are checked for general legitimacy before acceptance. That means we have about a 50% acceptance rate for ideas. After submission, there is a kind of post-publication review in the sense that readers can rate a submission by "liking" the submission, or can leave a comment on the submission.

  3.  There is no publication cost. All costs of running the journal are absorbed personally by the founders.

Regards,
David Harris
