### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by samhefnawy** [openjournals/brief-ideas#157]
Hi Editor,

I have sent an idea and it has been rejected.
The following link for it: http://beta.briefideas.org/ideas/28c91c38101c8a6c9a8393456a440d9d
Titled : dynamic directory of all research tools

I appreciate if you help me to understand the publishing criteria to let my ideas flow and get publsihed with you? and in particualr what was wrong with my submitted one.

Thanks in advance for your help.

Regards 
Mohamed

**Comment by physicsdavid** [comment]
Hi Mohamed,

The reason this was rejected is that the idea in that submission is a very commonly expressed one and most subfields of science have already developed directories like this. One overarching tool is just wikipedia's page on science software: https://en.wikipedia.org/wiki/Category:Science_software. This has an easily updateable list of tools, and allows you to get alerts to changes in the list. There is already a volunteer "steering group" in the form of wikipedia editors. In addition, most subfields fairly regularly publish review articles of the most useful and effective software relevant to their field.

So although the idea is a good one, it's not clear how the submitted paper shows something that is new. If you wished to clarify what is new and builds on what already exists, then it could be a suitable contribution to the journal.

Regards,
David
