### ISSUE TITLE
Having trouble with wordcount

### ISSUE THREAD

**Issue by markturner6** [openjournals/brief-ideas#161]
I am trying to submit a new idea. The word count on the "A brief idea" block said 200 and when I pressed "Save Idea" a red block appeared saying "Body Your idea must be less than 200 words." I then took out a word making the word count block 199, and tried saving it with the same result. I am uncertain why I am getting this error. Thanks for your help.

Mark Turner
markturner6@gmail.com

**Comment by arfon** [comment]
Hi @markturner6, apologies for the very slow reply. Could you try again now?

**Comment by markturner6** [comment]
Thank you very much. I am completely tied up on another project right now,
but will test it again in a short while.

Thanks again,
Mark Turner
