### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by PerigGouanvic** [openjournals/brief-ideas#169]
I would like to cancel a submission. How should i proceed?

**Comment by physicsdavid** [comment]
I can just reject it now but I'd be interested to know the reason for cancelling it. (I don't need specifics, but just out of curiosity is it because you don't think the idea is solid, you've found somebody else has had it, you're planning on trying to publish it elsewhere, etc.)

Thanks,
David

**Comment by PerigGouanvic** [comment]
Somebody else had a very similar idea (but not in the JBI). I could rewrite entirely my idea to emphasize some aspects that are distinctive (I came to the idea through a different route), but I'll give myself some time to avoid doing other mistakes.

Thanks

**Comment by physicsdavid** [comment]
Thanks for the extra info - it always helps to hear that sort of thing. We encourage incremental ideas so if you have something that goes beyond the other work and builds on it in some way, then please submit it (with a reference to the other work). Thanks!
