### ISSUE TITLE
The benefit of voting

### ISSUE THREAD

**Issue by Esraa-Hassanein** [openjournals/brief-ideas#180]
Hello,

I'd like to ask about the benefit of voting for an idea, how would this be valuable?

Also, I wonder if the journal of brief ideas has an impact factor!

Sincerely,
Esraa

**Comment by arfon** [comment]
Voting is already possible! I’m not sure we’re ever going to try and calculate and impact factor sorry. @physicsdavid ?

**Comment by Esraa-Hassanein** [comment]
I know that voting is possible. My question was about can voting help in publishing my idea? Why voting is important?

Sent from Yahoo Mail on Android 
 
  On السبت, مايو ٢, ٢٠٢٠ at ١١:١٨ م, Arfon Smith<notifications@github.com> wrote:   


Voting is already possible! I’m not sure we’re ever going to try and calculate and impact factor sorry. @physicsdavid ?

**Comment by physicsdavid** [comment]
To address the voting issue first: Voting is primarily a way for people to express that they find an idea interesting. It does not particularly feed into any kind of promotional value for the ideas although one of the views of the ideas does show more-voted ideas higher in the list.

As for Impact Factor: I don't think we'll have the capacity to calculate Impact Factor ourselves, to be honest, unless somebody would like to build a way for us to do that. Even then, to be honest, I don't think Impact Factor is particularly useful metric for us and even works against our goals, as we are not trying to establish some kind of advertising for the journal as such (which is really the effect of a journal's Impact Factor). We would prefer the focus be on the ideas themselves.

In practice, the Impact Factor of a journal seems to be primarily used as a (weak) proxy for the quality of individual papers (such as by hiring, promotion, and tenure committees). That is clearly not warranted in general, and I personally have no real interest into buying into that system. A big part of our journal's philosophy is that the conventional publishing system is broken in various ways. This journal is an intervention into that system that doesn't necessarily play by all those rules. 

Our Impact Factor would be quite low, to be honest. But we have plenty of anecdotal evidence that the value of the journal isn't best measured through conventional citation measures but through less quantifiable measures of influence, for example the establishment of other journals in the conventional research publishing ecosystem that adopt some of our conceptual basis.

If we were to create a quantifiable metric, I think a more valuable one than the number of citations in this journal would be the length of the chain of citations from the paper, which is much more difficult but possible to calculate. The power of brief ideas is to prompt more ideas, which then prompt more ideas. It is not about establishing a body of work that is necessarily used in lots of cases but that individual ideas might be important in setting of a chain of ideation that leads to significant results.
