### ISSUE TITLE
MathJax blocked

### ISSUE THREAD

**Issue by cranmer** [openjournals/brief-ideas#183]
When I try to view 
https://beta.briefideas.org/ideas/5c2f74aedbf3618ca180382e393c7617
the LaTeX doesn't render with MathJax.

It looks like this is the problem:
```
[blocked] The page at https://beta.briefideas.org/ideas/5c2f74aedbf3618ca180382e393c7617 was not allowed to run insecure content from http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML.
```

**Comment by arfon** [comment]
Thanks for spotting this @cranmer. Fixed in https://github.com/openjournals/brief-ideas/commit/e8fb4afa8d6fb3b54bbdc766580ba2ff9944cafa

**Comment by cranmer** [comment]
Thanks!
