### ISSUE TITLE
Decision Timeline

### ISSUE THREAD

**Issue by flippingartist** [openjournals/brief-ideas#184]
Dear Editor,
Around six months ago I submitted an idea to this truly great Journal of Brief Ideas, and am waiting for a decision. That's fine; however, the idea has since developed and grown, as Covid allowed for time to research and write a full manuscript. The manuscript was recently submitted to a print/online journal and is currently being peer reviewed. The idea submitted to the Journal of Brief Ideas is one small paragraph of the manuscript, and not the overall point of the manuscript. They are different but related. On its own, without the related research, the idea submitted to the Journal of Brief  Ideas may appear far fetched, or confusing. This may be why it is taking awhile for a decision. It would be fine if it is rejected, or it would be fine if it was accepted. Just wondering how long it may take. 
Thank you so much for this Journal!!

**Comment by physicsdavid** [comment]
Hi @flippingartist, what name did you use for the submission, or what was the title of it. I can't see any unprocessed submissions from that time period at all. If you give me a little more information on it, I can try to figure out where it went.

Thanks,
David

**Comment by flippingartist** [comment]
Hi David, it was about the Cups and Rings Stones in the British Isles, March 4.
Thanks so much

**Comment by physicsdavid** [comment]
My apologies for missing it in among the other submissions. I have processed it now and should see it published.
Regards,
David

**Comment by flippingartist** [comment]
Dear David,
Thank you so much. This is great news!
Have a great weekend,
Erica
