### ISSUE TITLE
BUG: Sign-in with ORCID

### ISSUE THREAD

**Issue by tupui** [openjournals/brief-ideas#195]
Seems to be broken, I contacted ORCID's support and they told me it was on your side:

<img width="574" alt="Screenshot 2021-03-11 at 08 49 23" src="https://user-images.githubusercontent.com/23188539/110753329-be7b3800-8246-11eb-95c0-5f71f671475b.png">

**Comment by tupui** [comment]
cc @arfon

**Comment by arfon** [comment]
This should be fixed with https://github.com/openjournals/brief-ideas/commit/1aa42e27b729c0881ea7ff2a093ff245cfbda2b6. Please let me know if you're still experiencing issues.

**Comment by tupui** [comment]
Great I can log in now, thanks!
