### ISSUE TITLE
Submitted idea on March 4th

### ISSUE THREAD

**Issue by chrismccrum** [openjournals/brief-ideas#196]
Hello,

I submitted this on March 4th and it is not yet screened by the editors: https://beta.briefideas.org/ideas/4582e686fa9babba50605ebf45471fc0

Not sure what the typical timescale is but it would be great if the editors could take a look!

Thanks!

**Comment by physicsdavid** [comment]
Apologies for the delay in pressing the right buttons! It should now show as accepted.
