### ISSUE TITLE
Requesting review of my idea

### ISSUE THREAD

**Issue by Dattatreya1997** [openjournals/brief-ideas#197]
I had written one idea and its been a long time, I didn't received any mail and still it is showing Editorial clearance is needed. It will be very helpful if you can review m idea. 
https://beta.briefideas.org/ideas/4c98c95cf0f4fdca709d6432ab8a9352

**Comment by jensharbers** [comment]
I have same issue with two of my ideas.

http://beta.briefideas.org/ideas/c09810cd5984a96d1860a6c7c0cd3c59

Is the Journal still active?

And 

http://beta.briefideas.org/ideas/7d5007cfc09d9b9f7958eb6d8ffb5dac
