### ISSUE TITLE
Is this journal still being maintained?

### ISSUE THREAD

**Issue by sgbaird** [openjournals/brief-ideas#205]
There seem to be many people asking for reviews of the ideas they submitted a while back, and I'm noticing many open issues that haven't been responded to.

**Comment by sgbaird** [comment]
@arfon @physicsdavid

**Comment by arfon** [comment]
I'm still providing technical support but @physicsdavid  use responsible for editorial work.

**Comment by ianfhunter** [comment]
You can see editorial activity here:
https://beta.briefideas.org/ideas.atom
