### ISSUE TITLE
How long will it take to know whether the idea is accepted or not ?? Does this Journal function now ??

### ISSUE THREAD

**Issue by Kapila-Premarathne** [openjournals/brief-ideas#207]
How long will it take to know whether the idea is accepted or not ?? Does this Journal  function now ??

**Comment by physicsdavid** [comment]
Apologies for the delay as I have been ill and unable to process some submissions. Yours should be refereed now.

**Comment by Kapila-Premarathne** [comment]
Thank you for the prompt reply. So sorry hear you're not feeling well.
