### ISSUE TITLE
Error on submitting

### ISSUE THREAD

**Issue by ntnsndr** [openjournals/brief-ideas#211]
I love this project! 

I just created an idea, and got an edit link. However, when I try to submit, I get this error: 

```
We're sorry, but something went wrong.
If you are the application owner check the logs for more information.
```
Not sure what else to share, but let me know if you need more info to reproduce the error.

**Comment by cobra1234-lab** [comment]
I got the same error and I don't understand why

**Comment by arfon** [comment]
This should now be fixed. Apologies!
