### ISSUE TITLE
Problem cannot submit

### ISSUE THREAD

**Issue by cobra1234-lab** [openjournals/brief-ideas#212]
When I try to submit my idea, I get a message:

"We're sorry, but something went wrong.
If you are the application owner check the logs for more information."

How do I fix this?

**Comment by cobra1234-lab** [comment]
@arfon @physicsdavid

**Comment by arfon** [comment]
I'm afraid there's an issue with the site currently blocking new submissions. We're working on a fix for this but currently don't have an ETA.

**Comment by arfon** [comment]
This should now be fixed. Apologies!
