### ISSUE TITLE
Do brief ideas already submitted to the Journal on figshare need re-ingesting?

### ISSUE THREAD

**Issue by drphilmarshall** [openjournals/brief-ideas#26]
There are two published brief ideas here about the JOBI concept:

http://briefideas.org/about

and then two more here:

http://figshare.com/articles/search?q=tag%3A+Journal%20of%20Brief%20Ideas&quick=1

It could be nice to have these as the beta examples! 
Great stuff :-)

**Comment by physicsdavid** [comment]
We'll just re-enter any old ideas worth saving.
