### ISSUE TITLE
Search while entering a brief idea

### ISSUE THREAD

**Issue by physicsdavid** [openjournals/brief-ideas#33]
It would be very useful to have a search capability while entering a brief idea so that you could find and reference related ideas. In addition it would be great to have an auto-search for related ideas based on similarities in the text you have entered with a search of the database.

**Comment by arfon** [comment]
Moving this to the [Beta release](https://github.com/openjournals/brief-ideas/milestones/Beta%20release) milestone. @stuartlynn - how was this looking? Is there a pull request for any of this?

**Comment by stuartlynn** [comment]
What I have is in the similar_articles branch (https://github.com/openjournals/brief-ideas/tree/similar_articles) It sort of works... it matches other articles but I am not sure how good it is at finding properly similar articles. It was kind of hard to test that cause its such a vague criteria.

This is just the backend implementation with an end point. No front end integration but that shouldnt be hard to add

**Comment by stuartlynn** [comment]
The test that is failing on is the one that makes me think its not selecting particularly relevant ideas thought the ones in there might simple just be not complex enough.

**Comment by arfon** [comment]
I've opened up a PR for this branch here: https://github.com/openjournals/brief-ideas/pull/61
