### ISSUE TITLE
Idea previews should be run through HTML pipeline

### ISSUE THREAD

**Issue by arfon** [openjournals/brief-ideas#49]
See the front page of the dev site - links aren't run through the HTML pipeline.

![screen shot 2014-12-22 at 8 42 51 pm](https://cloud.githubusercontent.com/assets/4483/5534033/2660066a-8a1b-11e4-879f-6cd1e8d1e996.png)

**Comment by stuartlynn** [comment]
Did that pull request not resolve the issue?

**Comment by arfon** [comment]
Nah: 

![screen shot 2015-01-05 at 7 52 00 am](https://cloud.githubusercontent.com/assets/4483/5615397/c24b4208-94af-11e4-8e89-96c54023841e.png)

It turned out that we were truncating the string after the content had been going through the HTML pipeline and so this ended up producing invalid HTML. https://github.com/openjournals/brief-ideas/pull/60 fixes this I believe.
