### ISSUE TITLE
Add trending page for highly-ranked ideas

### ISSUE THREAD

**Issue by arfon** [openjournals/brief-ideas#56]
Basically we just need to sort by 'score' here. Should this be the default of a different view?

**Comment by physicsdavid** [comment]
I think a different view as when you have the top ranked list, those items tend to accumulate even higher rankings and there is a runaway effect that leaves a long tail undiscovered.

**Comment by arfon** [comment]
> I think a different view as when you have the top ranked list, those items tend to accumulate even higher rankings and there is a runaway effect that leaves a long tail undiscovered.

Agreed. I'm planning on making this a different view.

**Comment by arfon** [comment]
Fixed in https://github.com/openjournals/brief-ideas/pull/59
