### ISSUE TITLE
can I post a figure with my idea?

### ISSUE THREAD

**Issue by davidwhogg** [openjournals/brief-ideas#66]

**Comment by arfon** [comment]
You can embed a link to an image - we currently don't archive image links with the idea text in Zenodo though so I don't recommend this :-/

**Comment by davidwhogg** [comment]
How hard would it be?

**Comment by arfon** [comment]
> How hard would it be?

No hugely hard to implement on this side but I'd like to hear from @lnielsen about how we would then go about depositing this into Zenodo properly. @lnielsen - can I pass a URL to an image when depositing a record or do you need the _actual_ image posted to you?

**Comment by lnielsen** [comment]
I currently need the image posted to ``https://zenodo.org/api/deposit/depositions/:id/files`` (see https://zenodo.org/dev#restapi-res-files) 

It should be possible in the future to tell the same API to just go get the file from somewhere but it might take a bit before it's implemented.

**Comment by arfon** [comment]
> It should be possible in the future to tell the same API to just go get the file from somewhere but it might take a bit before it's implemented.

I don't suppose I can just give you a URL to an object on S3 yet can I? :pray:

**Comment by arfon** [comment]
Fixed in #122. You can now attach a single file to an idea. These don't show up inline (yet) as they could be images or data but it's now possible to attach a file to the idea.
