### ISSUE TITLE
how do I submit a multi-author idea?

### ISSUE THREAD

**Issue by davidwhogg** [openjournals/brief-ideas#67]

**Comment by arfon** [comment]
Currently this isn't possible.

**Comment by davidwhogg** [comment]
Don't close this one, b/c I am *sure* my first contribution will be in collaboration with @drphilmarshall

**Comment by drphilmarshall** [comment]
Looks like we now need to have a brief idea together, Hogg.

**Comment by arfon** [comment]
> Looks like we now need to have a brief idea together, Hogg.

Indeed. It's live :boom:

**Comment by drphilmarshall** [comment]
Hmm - I couldn't see where to add co-authors on the "New Idea" form. So I
opened an issue on the search box instead :-)

**Comment by arfon** [comment]
@drphilmarshall this actually happens after you save the draft:

https://cloud.githubusercontent.com/assets/4483/7994770/ac3584be-0ad5-11e5-9b2c-8153f7c3ffe7.gif

**Comment by drphilmarshall** [comment]
Ah, I see! Maybe put a note to that effect somewhere on the New Idea form?

**Comment by arfon** [comment]
Yeah. Good idea.

**Comment by davidwhogg** [comment]
awesome and well done, @arfon!
