### ISSUE TITLE
When I click on DOI for article I get a not-authorized at Zenodo  

### ISSUE THREAD

**Issue by stuartlynn** [openjournals/brief-ideas#72]
@arfon  any ideas why this is happening?
![screen shot 2015-02-09 at 12 12 22 am](https://cloud.githubusercontent.com/assets/209838/6101811/646ecc98-aff0-11e4-9e22-d534918bd69c.png)

**Comment by arfon** [comment]
This is because each entry into Zenodo needs manually approving (which I've now done) - @lnielsen - anything we can do about this?

**Comment by lnielsen** [comment]
Nope it's all on my site.
