### ISSUE TITLE
Can I edit a post after publishing?

### ISSUE THREAD

**Issue by cranmer** [openjournals/brief-ideas#75]
or can I have a "sock" -> "stock" button ;-)

I'm not sure if I should edit at Zenodo, or if it's too late since DOI is minted.

**Comment by arfon** [comment]
Sorry @cranmer, ideas are immutable after posting.

**Comment by arfon** [comment]
> I'm not sure if I should edit at Zenodo

@lnielsen - is it possible to edit on your end? Would this make a new version?

**Comment by cranmer** [comment]
This makes sense. 
It might be worth mentioning in the about and new idea page.

**Comment by arfon** [comment]
Yeah, I warned against this in the video :smile: To be honest we were planning on adding some more docs once people have submitted a few ideas. I agree this is important though.
