### ISSUE TITLE
Editorial features, or flagging nonsense?

### ISSUE THREAD

**Issue by jradavenport** [openjournals/brief-ideas#81]
Despite requiring ORCID for log-in, [early posts](http://ideas.theoj.org/ideas/48d1a46509105f5fcd27ae581f8a0735) seem to indicate that nonsense is allowed. While I believe humor should undoubtedly be a part of the spirit of this Journal, a large fraction of garbage will lead to the service being abandoned.

I am not sure the best means for this. Models could include:

- all posts moderated (laborious)
- Posting under real name only
- account by invitation only, or requiring verification
- community moderation, e.g. a "down vote" button
- a "Report as Spam" button to raise flags to admins

**Comment by arfon** [comment]
Yep, agreed. See #83 for my response to this. Posts like these will be 'muted', not deleted.

**Comment by arfon** [comment]
OK, this is now fixed. Let's see how this goes. If it gets bad then we could add in some additional checks.

**Comment by arfon** [comment]
/ cc @physicsdavid
