### ISSUE TITLE
Feature Request: dismiss ideas

### ISSUE THREAD

**Issue by IanMulvany** [openjournals/brief-ideas#86]
As as logged in reader 
I want to discard ideas I have browsed and am not interested in 
So that When I return to the site I only see either new ideas or ideas I am interested in

**Comment by arfon** [comment]
So not bookmarking? More 'get rid of this, I don't want to see it again'

**Comment by IanMulvany** [comment]
Exactly, if I'm interested in evaluating new ideas how do I efficiently triage them? I need a way to dismiss the already triaged ones.

**Comment by arfon** [comment]
I'll probably deploy this tomorrow.

**Comment by arfon** [comment]
@IanMulvany this is now live. Just click the 'hide' button to stop seeing ideas.

![screen shot 2015-02-18 at 8 36 36 am](https://cloud.githubusercontent.com/assets/4483/6251551/5c64603e-b749-11e4-840f-f2f318805e6d.png)
