### ISSUE TITLE
Initial review of material

### ISSUE THREAD

**Issue by BillGrey1987** [openjournals/brief-ideas#89]
Dear Journal of Brief Ideas,

I came across your journal recently and thought it was a very good idea, with some very interesting prospects for the future.
I am interested to know how the initial "review" takes place. For example, does one person read all the little abstracts and verify what they are saying is true? do you allow references within the work (at the end and not in the word count of course)? do you have people checking the submissions who are specifically in the area/work in the larger field of science themselves?
Would you be interested in having someone review articles submitted in the field of biology or medicine specifically in the future?

Kind regards,

William Grey

**Comment by arfon** [comment]
/ cc @physicsdavid

**Comment by physicsdavid** [comment]
Dear William,

Thanks for your interest!

At the moment, I read all the papers submitted and remove anything that doesn't adhere to our standards for publication but that doesn't necessarily include a proper check on whether everything is true. It removes blatantly false/offensive papers or entries that don't appear to advance research in their field but isn't a full peer review.

References are allowed and you will see some entries have made plentiful use of the ability to reference (e.g. http://beta.briefideas.org/ideas/60ce1d1ca8e506beecdcbbf186d38766) These references do not count toward the word limit.

We are indeed interested in having people review articles in the future but haven't started that process yet. Perhaps you could email me at physicsdavid at gmail.com and we can discuss the review process further.

Thanks,
David

**Comment by BillGrey1987** [comment]
Dear David,

I sent the below message to your gmail address. I haven't heard from you in a few days, and I am wondering if you have received it?

Kind regards,

Bill

Dear David,

Thanks for the quick reply.

I am coming towards the end of my PhD at King's College London, in the Department of Medical and Molecular Genetics. I have published one paper, have another under review and I am close to submitting a third (hopefully this year). I would be quite interested in getting involved in a smaller journal such as this one, as I intend to carry on working in academia as a post doc, and I think it would be something really interesting to be involved in, and would help me develop my career further at the same time.

I really like the idea of your brief ideas journal. It is something I might be considering submitting a few short pieces to in the future, as a lot of the work I do in the clinic goes unpublished, and, in reference to my publications, I could put a bit more information out there about some of the things that never quite made it out for one reason or another. Likewise, I would quite like to be able to put some short pieces out about my mouse model, as I won't be carrying on with it after I finish my PhD, and there are some interesting bits of information that could  be useful to others.

If you would be interested in having someone from my field of science working with you on this, I would really like to be considered, and to talk to you further about it. I have experience with writing grants and papers and replying to reviewer comments, but clearly I am not highly experienced, so I would see this as an opportunity to both contribute to the growth of your journal, and learn a bit more about the process of reviewing authors work and interacting with them over this.

Kind regards,

Bill



William Grey

Department of Medical and Molecular Genetics
Division of Genetics and Molecular Medicine
King's College London School of Medicine
Floor 8 Tower Wing
Guy's Hospital
London SE1 9RT
UK

Email: william.grey@kcl.ac.uk<mailto:william.grey@kcl.ac.uk>






On 16 Feb 2015, at 19:24, physicsdavid <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear William,

Thanks for your interest!

At the moment, I read all the papers submitted and remove anything that doesn't adhere to our standards for publication but that doesn't necessarily include a proper check on whether everything is true. It removes blatantly false/offensive papers or entries that don't appear to advance research in their field but isn't a full peer review.

References are allowed and you will see some entries have made plentiful use of the ability to reference (e.g. http://beta.briefideas.org/ideas/60ce1d1ca8e506beecdcbbf186d38766) These references do not count toward the word limit.

We are indeed interested in having people review articles in the future but haven't started that process yet. Perhaps you could email me at physicsdavid at gmail.com<http://gmail.com> and we can discuss the review process further.

Thanks,
David

**Comment by physicsdavid** [comment]
Hi William,

I did receive your email and sorry for being slow to reply. There is a lot
going on for me right now!

I am definitely interested in involving you further but give me a little
time to work out the best way. I have some ideas though.

Best wishes,
David

**Comment by BillGrey1987** [comment]
Hi David,

Not a problem, I just wanted to make sure the email had gone to the right place. I will await your email.

All the best,

Bill

**Comment by arfon** [comment]
Closing this as I think this conversation is also happening in email.

**Comment by physicsdavid** [comment]
Hi Bill,

We're working on making some extensions to the journal to make it useful
for other editors to take part. The plan I have at the moment is to have
editors in various fields make an "editor's choice" selection of papers
that they think are worthwhile. That designation will show up on the paper
and also increase its rating so it will be higher on the Trending Ideas
page. When we have that built I'd be interested in having you as one of
those editors. The role for editors might expand beyond that in the future,
depending on the quantity of submissions.

Best wishes,
David
