### ISSUE TITLE
tooltips?

### ISSUE THREAD

**Issue by sckott** [openjournals/brief-ideas#94]
Curious if you have any plans to use tooltips?  E.g., on the Vote and Hide buttons, I wasn't sure what they mean (What does a vote mean?, What does hide mean? Can I unhide? Can I undo my vote?) A short tooltip would be cool

**Comment by arfon** [comment]
> A short tooltip would be cool

Agreed. We should definitely have these. We're a little short on docs all round to be honest :-\

**Comment by sckott** [comment]
:+1:
