### ISSUE TITLE
Journal information in content submission to Zenodo

### ISSUE THREAD

**Issue by physicsdavid** [openjournals/brief-ideas#97]
Should we add the Journal information to the submission to Zenodo so that if somebody comes across the a brief idea in Zenodo, they know it came from the Journal originally? I'm imagining just a line or two and citation (if we can get the DOI prior to actual submission).

Something like:
The paper was originally published in the Journal of Brief Ideas on Feb 1, 2015. It is licensed under a Creative Commons Attribution CC-BY license. 
Reference: Name, (2015), "The title of my idea", Journal of Brief Ideas, Published on Feb 1, 2015. DOI: 10.5281/zenodo.11111

**Comment by arfon** [comment]
@lnielsen - any suggestions on how we should do this?

**Comment by lnielsen** [comment]
Take a look at https://zenodo.org/record/14765

If you add a link in the related identifiers starting with http://ideas.theoj.org/ (actually are we using beta.briefideas.org or ideas.theoj.org?) it will add the logo.

The "Cite as" needs to be worked on though as it currently includes Zenodo.


In the API you just need to set: 

```
...
'related_identifiers': [{'relation': 'isIdenticalTo', 'identifier':'http://ideas.theoj.org/ideas/17b997da912f99ce9988a47f42b52692'}]
...
```

I can fill the backlog of ideas with the correct URL.

**Comment by arfon** [comment]
OK I've added these `related_identifiers` now.

@lnielsen - could you update the existing records to add these? Also, yes, the URL is `beta.briefideas.org`
